import '../models/video_models.dart';
import '../models/user_model.dart';
import '../models/reaction_models.dart';

class MockVideoData {
  static List<VideoPost> getMockVideos() {
    return [
      VideoPost(
        id: '1',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
        thumbnailUrl: 'https://picsum.photos/400/600?random=1',
        creator: User(
          id: '1',
          name: 'Alex Fitness',
          age: 28,
          bio: 'Fitness enthusiast 💪',
          profilePic: 'https://picsum.photos/100/100?random=1',
          coverImage: 'https://picsum.photos/800/400?random=1',
          isVerified: true,
          isFollowing: false,
          joinedAt: DateTime.now().subtract(const Duration(days: 365)),
          interests: ['HIIT', 'Strength'],
          followers: 1200,
          following: 300,
          posts: [],
          stats: UserStats(
            totalPosts: 45,
            followers: 1200,
            following: 300,
            totalViews: 15420,
          ),
          achievements: [],
        ),
        title: '5-Minute Morning HIIT 🔥',
        description: 'Start your day with this energizing HIIT workout!',
        tags: ['HIIT', 'Morning', 'Cardio', 'QuickWorkout'],
        workoutType: 'HIIT',
        difficulty: 'Intermediate',
        duration: 300,
        views: 15420,
        shares: 234,
        comments: 67,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        isFollowing: false,
        reactionSummary: ReactionSummary.fromReactions([
          Reaction(
            id: '1',
            userId: 'user1',
            userName: 'John',
            userAvatar: 'https://picsum.photos/50/50?random=1',
            type: ReactionType.fire,
            createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
          ),
          Reaction(
            id: '2',
            userId: 'user2',
            userName: 'Sarah',
            userAvatar: 'https://picsum.photos/50/50?random=2',
            type: ReactionType.strong,
            createdAt: DateTime.now().subtract(const Duration(minutes: 15)),
          ),
          Reaction(
            id: '3',
            userId: 'user3',
            userName: 'Mike',
            userAvatar: 'https://picsum.photos/50/50?random=3',
            type: ReactionType.fire,
            createdAt: DateTime.now().subtract(const Duration(minutes: 10)),
          ),
        ], 'current_user_id'),
        recommendations: [
          Recommendation(
            id: '1',
            userId: 'user4',
            userName: 'Emma',
            userAvatar: 'https://picsum.photos/50/50?random=4',
            createdAt: DateTime.now().subtract(const Duration(minutes: 25)),
          ),
        ],
        isRecommended: false,
      ),
      
      VideoPost(
        id: '2',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        thumbnailUrl: 'https://picsum.photos/400/600?random=2',
        creator: User(
          id: '2',
          name: 'Yoga Flow',
          age: 25,
          bio: 'Yoga instructor 🧘‍♀️',
          profilePic: 'https://picsum.photos/100/100?random=2',
          coverImage: 'https://picsum.photos/800/400?random=2',
          isVerified: false,
          isFollowing: true,
          joinedAt: DateTime.now().subtract(const Duration(days: 200)),
          interests: ['Yoga', 'Mindfulness'],
          followers: 850,
          following: 200,
          posts: [],
          stats: UserStats(
            totalPosts: 32,
            followers: 850,
            following: 200,
            totalViews: 8500,
          ),
          achievements: [],
        ),
        title: 'Relaxing Evening Yoga 🧘‍♀️',
        description: 'Unwind with this peaceful yoga session',
        tags: ['Yoga', 'Evening', 'Relaxation', 'Mindfulness'],
        workoutType: 'Yoga',
        difficulty: 'Beginner',
        duration: 600,
        views: 8920,
        shares: 156,
        comments: 43,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        isFollowing: true,
        reactionSummary: ReactionSummary.fromReactions([
          Reaction(
            id: '4',
            userId: 'user5',
            userName: 'Lisa',
            userAvatar: 'https://picsum.photos/50/50?random=5',
            type: ReactionType.love,
            createdAt: DateTime.now().subtract(const Duration(minutes: 40)),
          ),
          Reaction(
            id: '5',
            userId: 'user6',
            userName: 'David',
            userAvatar: 'https://picsum.photos/50/50?random=6',
            type: ReactionType.love,
            createdAt: DateTime.now().subtract(const Duration(minutes: 20)),
          ),
        ], 'current_user_id'),
        recommendations: [],
        isRecommended: false,
      ),
      
      VideoPost(
        id: '3',
        videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
        thumbnailUrl: 'https://picsum.photos/400/600?random=3',
        creator: User(
          id: '3',
          name: 'Strength Coach',
          age: 32,
          bio: 'Strength & conditioning coach 💪',
          profilePic: 'https://picsum.photos/100/100?random=3',
          coverImage: 'https://picsum.photos/800/400?random=3',
          isVerified: true,
          isFollowing: false,
          joinedAt: DateTime.now().subtract(const Duration(days: 500)),
          interests: ['Strength', 'Conditioning'],
          followers: 2100,
          following: 150,
          posts: [],
          stats: UserStats(
            totalPosts: 78,
            followers: 2100,
            following: 150,
            totalViews: 25000,
          ),
          achievements: [],
        ),
        title: 'Full Body Strength Training 💪',
        description: 'Build muscle with this comprehensive strength workout',
        tags: ['Strength', 'FullBody', 'Muscle', 'Gym'],
        workoutType: 'Strength',
        difficulty: 'Advanced',
        duration: 1800,
        views: 22300,
        shares: 445,
        comments: 89,
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        isFollowing: false,
        reactionSummary: ReactionSummary.fromReactions([
          Reaction(
            id: '6',
            userId: 'user7',
            userName: 'Tom',
            userAvatar: 'https://picsum.photos/50/50?random=7',
            type: ReactionType.strong,
            createdAt: DateTime.now().subtract(const Duration(minutes: 60)),
          ),
          Reaction(
            id: '7',
            userId: 'user8',
            userName: 'Anna',
            userAvatar: 'https://picsum.photos/50/50?random=8',
            type: ReactionType.fire,
            createdAt: DateTime.now().subtract(const Duration(minutes: 35)),
          ),
          Reaction(
            id: '8',
            userId: 'user9',
            userName: 'Chris',
            userAvatar: 'https://picsum.photos/50/50?random=9',
            type: ReactionType.strong,
            createdAt: DateTime.now().subtract(const Duration(minutes: 12)),
          ),
        ], 'current_user_id'),
        recommendations: [
          Recommendation(
            id: '2',
            userId: 'user10',
            userName: 'Jake',
            userAvatar: 'https://picsum.photos/50/50?random=10',
            createdAt: DateTime.now().subtract(const Duration(minutes: 45)),
          ),
          Recommendation(
            id: '3',
            userId: 'user11',
            userName: 'Sophie',
            userAvatar: 'https://picsum.photos/50/50?random=11',
            createdAt: DateTime.now().subtract(const Duration(minutes: 30)),
          ),
        ],
        isRecommended: true,
      ),
    ];
  }
}